### PR TITLE
Fix for missing implicit modifier in classlikes

### LINKED ISSUE #202: Objects don't display "implicit" modifier
See https://scala3doc.s3.eu-central-1.amazonaws.com/pr-master/example-project/example-project/example/-named-type-arguments/list-functor/index.html.

### PR DESCRIPTION
**Pull request by pikinier20**
closes #202

### CODE REVIEW

File: src/main/scala/dotty/dokka/tasty/BasicSupport.scala [hunk 1]
```diff
@@ -104,6 +104,18 @@ class SymOps[R <: Reflection](val r: R):
       symbol.is(dotc.core.Flags.Open)
     }
 
+    def hackFlagsForImplicitClasslikes: Seq[Modifier] =
+      if sym.isClassDef && (
```
Comment (romanowski) [inline src/main/scala/dotty/dokka/tasty/BasicSupport.scala]: Could we pull components of this if into methods for readablity? Also if I am not mistaken it will add `implicit` to `B` here:

```
object A:
  class B
  implicit object B
```

File: src/main/scala/dotty/dokka/tasty/BasicSupport.scala [hunk 2]
```diff
@@ -115,8 +127,11 @@ class SymOps[R <: Reflection](val r: R):
         Flags.Lazy -> Modifier.Lazy,
         Flags.Override -> Modifier.Override,
         Flags.Case -> Modifier.Case,
-        ).collect { case (flag, mod) if sym.flags.is(flag) => mod }
+        ).collect {
```
Comment (romanowski) [inline src/main/scala/dotty/dokka/tasty/BasicSupport.scala]: why this change? Was it an autoformat?

**Review by romanowski — CHANGES_REQUESTED** [review]

File: src/main/scala/dotty/dokka/tasty/BasicSupport.scala (hunk 2 above)
Comment (pikinier20) [reply src/main/scala/dotty/dokka/tasty/BasicSupport.scala]: Idk, probably I was debugging sth and rewrote it this way, refactored

File: src/main/scala/dotty/dokka/tasty/BasicSupport.scala (hunk 1 above)
Comment (pikinier20) [reply src/main/scala/dotty/dokka/tasty/BasicSupport.scala]: Yea, that was true, but fixed that. Separated conditions into methods

File: src/main/scala/dotty/dokka/tasty/BasicSupport.scala [hunk 3]
```diff
@@ -104,6 +104,15 @@ class SymOps[R <: Reflection](val r: R):
       symbol.is(dotc.core.Flags.Open)
     }
 
+    def hackFlagsForImplicitClasslikes: Seq[Modifier] =
+      def implicitObjectCondition = sym.flags.is(Flags.Object) && sym.companionModule.flags.is(Flags.Implicit)
+      def implicitClassCondition = sym.owner.isClassDef && sym.owner.classMethods.exists(m => 
+        m.name == sym.name && m.flags.is(Flags.Synthetic & Flags.Implicit)
+      )
+      if sym.isClassDef && (implicitObjectCondition || implicitClassCondition)
```
Comment (romanowski) [inline src/main/scala/dotty/dokka/tasty/BasicSupport.scala:112]: it looks really nice now :heart:

**Review by romanowski — APPROVED** [review]

**Review by romanowski — CHANGES_REQUESTED** [review]
It seesm that this PR wants to re-introduce gradle... Please remove all non-related files.

**Comment by pikinier20** [comment]
Ok, I've got rid of gradle project and rebased branch
